# Generated by Django 2.2.2 on 2020-01-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
