# Generated by Django 2.2.2 on 2020-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(default='Images/None/NO_img.jpg', null=True, upload_to='Images/'),
        ),
    ]
