# Generated by Django 2.2.2 on 2020-01-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.FileField(default='Images/None/NO_img.jpg', upload_to='Images/'),
        ),
    ]
